//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doanmonhocweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuangCao
    {
        public int MaQC { get; set; }
        public string TieuDeQC { get; set; }
        public string HinhQC { get; set; }
        public Nullable<System.DateTime> NgayThem { get; set; }
    }
}
