//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doanmonhocweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanTriVien
    {
        public int Ma_QTV { get; set; }
        public string HoQTV { get; set; }
        public string TenQTV { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string TenDagNhapQTV { get; set; }
        public string MatKhauQTV { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Email { get; set; }
        public Nullable<int> Avatar { get; set; }
        public Nullable<int> QuyenQTV { get; set; }
    }
}
