//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doanmonhocweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.CTDATHANGs = new HashSet<CTDATHANG>();
        }
    
        public int Ma_Sach { get; set; }
        public string Ten_Sach { get; set; }
        public string Tac_Gia { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<double> GiaCuaHang { get; set; }
        public string Don_Vi_Tinh { get; set; }
        public Nullable<int> Ma_NXB { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> Ma_CD { get; set; }
        public string Mota { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public Nullable<int> SoLanXem { get; set; }
        public string HinhAnh { get; set; }
        public string Loai { get; set; }
        public string LoaiBia { get; set; }
        public Nullable<int> SoTrang { get; set; }
        public string NhaPhanPhoi { get; set; }
        public string Tieude { get; set; }
    
        public virtual ChuDe ChuDe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDATHANG> CTDATHANGs { get; set; }
        public virtual NXB NXB { get; set; }
    }
}
