//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doanmonhocweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VanPhongPham
    {
        public int Ma_VPP { get; set; }
        public string Ten_VPP { get; set; }
        public Nullable<double> Gia { get; set; }
        public string Don_Vi_Tinh { get; set; }
        public Nullable<int> Ma_NSX { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string Mota { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public Nullable<int> SoLanXem { get; set; }
        public string Anh { get; set; }
        public string PhanLoai { get; set; }
        public string Tieude { get; set; }
    
        public virtual NSX NSX { get; set; }
    }
}
